// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC_8xTaYrxtbR9uQ3eqaKl_pFGTY1poJFI',
    appId: '1:682847178807:web:6b312432c52e4b1bcbefb2',
    messagingSenderId: '682847178807',
    projectId: 'ecoevolve-auth-2148c',
    authDomain: 'ecoevolve-auth-2148c.firebaseapp.com',
    storageBucket: 'ecoevolve-auth-2148c.appspot.com',
    measurementId: 'G-QRWJEP63ZE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB608AVDCc26nrz31njUUu0zwsNUPVjGME',
    appId: '1:682847178807:android:de64edb411839313cbefb2',
    messagingSenderId: '682847178807',
    projectId: 'ecoevolve-auth-2148c',
    storageBucket: 'ecoevolve-auth-2148c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDfYT4qsmtiIQu9l9CQ1zQstWrTbFqee4Q',
    appId: '1:682847178807:ios:10fbb74a7b657088cbefb2',
    messagingSenderId: '682847178807',
    projectId: 'ecoevolve-auth-2148c',
    storageBucket: 'ecoevolve-auth-2148c.appspot.com',
    iosClientId: '682847178807-59b3nqbpj8uf02hh953hvj73gd64q9ip.apps.googleusercontent.com',
    iosBundleId: 'com.example.ecoevolve',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDfYT4qsmtiIQu9l9CQ1zQstWrTbFqee4Q',
    appId: '1:682847178807:ios:70cf57ba0f7787bbcbefb2',
    messagingSenderId: '682847178807',
    projectId: 'ecoevolve-auth-2148c',
    storageBucket: 'ecoevolve-auth-2148c.appspot.com',
    iosClientId: '682847178807-egiko6sgsmhb5d1i974p6u6csqt30tou.apps.googleusercontent.com',
    iosBundleId: 'com.example.ecoevolve.RunnerTests',
  );
}
